Vendor the Version package, use it instead of distutils
mwaskom/seaborn pull request #2659
Opened 2021-09-09 21:45 UTC by dannysepler

Closes https://github.com/mwaskom/seaborn/issues/2466. Unlike https://github.com/mwaskom/seaborn/pull/2485, this chooses to make a vendored Version class much like Pandas did here https://github.com/pandas-dev/pandas/pull/41207.

I took out a bit of what was in the Version class since it seemed like seaborn only needs to use the `Version` class, but happy to put it back in!

2021-09-09 22:24 UTC, mwaskom commented
Awesome! Yeah, I think this is the better path forward here.

2021-09-09 22:25 UTC, mwaskom commented
> it seemed like seaborn only needs to use the Version class

yep I think including the minimal amount possible to make this work is the right idea.

2021-09-10 00:28 UTC, mwaskom requested changes
Thanks! We're actually inside the window to bump the minimum version and strip out a lot of these conditionals, but let's not do that here. Only thing is to add the full text of the license.

2021-09-10 00:28 UTC, mwaskom commented on seaborn/external/version.py
> +under the terms of *both* these licenses.
Can you put a copy of the [BSD version](https://github.com/pypa/packaging/blob/main/LICENSE.BSD) of the license in `licenses/PACKAGING_LICENSE.md`?

2021-09-13 17:33 UTC, dannysepler commented
ready for review!

2021-09-13 23:33 UTC, mwaskom approved these changes

2021-09-13 23:33 UTC, mwaskom commented
Thanks @dannysepler!

2021-09-13 23:33 UTC, merged