Adding Grid.tick_params() method.
mwaskom/seaborn pull request #2944
Opened 2022-08-07 14:57 UTC by stefmolin

Closes https://github.com/mwaskom/seaborn/issues/2491

`FacetGrid` and `PairGrid` now have a `tick_params()` method, which will call the Matplotlib `tick_params()` on each of the `Axes` in the grid. Some examples:

```python
import seaborn as sns

tips = sns.load_dataset("tips")

g = sns.FacetGrid(tips, col="time",  row="sex")
g.map(sns.scatterplot, "total_bill", "tip")
g.tick_params(direction='in', length=6, width=2) # on both
g.tick_params(colors='blue', axis='x')
g.tick_params(colors='green', axis='y')
```
<img width="434" alt="Screen Shot 2022-08-07 at 10 51 44 AM" src="https://user-images.githubusercontent.com/24376333/183296876-efc260af-6cb7-4f0e-992a-09d58f951779.png">

```python
import seaborn as sns

penguins = sns.load_dataset('penguins')

g = sns.PairGrid(penguins, diag_sharey=False, corner=True)
g.map_lower(sns.scatterplot)
g.map_diag(sns.kdeplot)
g.tick_params(direction='in', length=6, width=2, color='blue')
```
<img width="673" alt="Screen Shot 2022-08-06 at 8 47 55 PM" src="https://user-images.githubusercontent.com/24376333/183270428-560914a3-08bf-4e82-b245-5b5dc48d26f6.png">

2022-08-07 14:58 UTC, stefmolin commented
I wasn't sure if you wanted to put this in the 0.12.0 release or the 0.13.0 release, so I held off on adding to the What's New for now. I also didn't add to the examples in case you wanted to either leave it out or had a specific change in mind. Let me know what you're thinking.

2022-08-07 18:37 UTC, mwaskom requested changes
Thanks @stefmolin, looks great, just a couple tiny comments.

2022-08-07 18:37 UTC, mwaskom commented on seaborn/axisgrid.py
> +    def tick_params(self, **kwargs):
Can we accept `axis` as a positional parameter like `Axes.tick_params` does?

2022-08-07 18:37 UTC, mwaskom commented on seaborn/axisgrid.py
> +        **kwargs
I think the `**` is going to mess up numpydoc formatting (I haven't build the docs to verify though).

2022-08-07 18:37 UTC, mwaskom commented on tests/test_axisgrid.py
> +                    assert tick.tick1line.get_color() == color
Nit, using `assert mpl.colors.same_color(tick.tick1line.get_color(), color)` would make this more robust if matplotlib coerces the internal color representation to rgba in the future.

2022-08-07 18:37 UTC, mwaskom commented on tests/test_axisgrid.py
> +        for ax in g.axes.ravel():
Super nit (more of an FYI): using `array.flat` is more idiomatic than `array.ravel()` for iteration.

2022-08-07 18:38 UTC, mwaskom commented
> I wasn't sure if you wanted to put this in the 0.12.0 release or the 0.13.0 release, so I held off on adding to the What's New for now.

This can go into 0.12 as I haven't cut a release candidate yet, so please update the release notes.

2022-08-09 00:58 UTC, stefmolin commented
Comments addressed and release notes updated. I also updated the usage of `ravel()` in the tests from my previous PR for `refline()`.

2022-08-09 21:45 UTC, mwaskom requested changes
Brilliant, thanks @stefmolin! Last bit, and sorry for missing this in my first review, but we should avoid accessing private matplotlib attributes as a general rule. I think the suggested change will work, and then this is 🟢🟢🟢

2022-08-09 21:45 UTC, mwaskom commented on tests/test_axisgrid.py
> +                    assert tick._width == width
```suggestion
                    assert tick.tick1line.get_linewidth() == width
```

2022-08-09 21:45 UTC, mwaskom commented on tests/test_axisgrid.py
> +                    assert tick._width == width
```suggestion
                    assert tick.tick1line.get_linewidth() == width
```

2022-08-09 23:28 UTC, mwaskom commented
Odd, I wonder why that didn't work.

Since matplotlib seems to be doing something weird here, probably best to use a different property. `pad` seems to work:

```python
ax = plt.gca()
ax.tick_params(pad=4.7)
yt, *_ = ax.yaxis.get_major_ticks()
print(yt.get_pad())
```
4.7

Feel free to change locally and force push over my attempt at a fix.

2022-08-10 00:47 UTC, stefmolin commented
Switched to `pad`, as suggested.

2022-08-10 00:56 UTC, mwaskom approved these changes

2022-08-10 00:56 UTC, merged

2022-08-10 00:56 UTC, mwaskom commented
Wonderful!