[Fix issue][#3511]lineplot of empty dataframe with hue in seaborn 0.13.0
mwaskom/seaborn pull request #3569
Opened 2023-11-22 16:37 UTC by Noko-Github

Corresponds to the case where grouping_var has None object.

Related issue: https://github.com/mwaskom/seaborn/issues/3511

2023-11-22 21:56 UTC, mwaskom commented
Thanks for taking a crack at this. Can you please add a test case that would fail with the current behavior (and pass with your fix)? Thanks!

2023-11-25 18:07 UTC, mwaskom requested changes
Thanks, a couple nitpicks but looks like the right approach.

2023-11-25 18:07 UTC, mwaskom commented on seaborn/_base.py
> +                grouping_keys.append(key)
Total nitpick, but the duplicate call to `levels.get` above looks cumbersome, maybe move the ternary down here? e.g.

```suggestion
                key = levels.get(var)
                grouping_keys.append([] if key is None else key)
```

2023-11-26 14:06 UTC, Noko-Github commented
Thank you for your review!
I incorporated feedback.

2023-11-28 00:29 UTC, mwaskom commented
Thanks @Noko-Github 

I think it's possible that this could also be fixed upstream by making the default `levels` value an empty list rather than `None`. I am not certain whether that would cause any other problems though and this is simple and seems to work so 👍

2023-11-28 00:29 UTC, mwaskom approved these changes

2023-11-28 00:29 UTC, merged

2023-11-28 00:30 UTC, mwaskom commented
Btw if you make the PR message say "Closes #issue" or "Fixes #issue" it will close the issue automatically when merged.